sudo: required
language: python
services:
    - docker
before_install:
    - sudo mkdir -p /data/log
    - pip install requests
script:
    - docker pull github.com/njuptaaa/noj_judgeserver.git
    - cp docker-compose.example.yml docker-compose.yml
    - docker-compose up -d
    - docker ps -a
    - sleep 5
    - python tests/tests.py
