version: "3"
services:
    judge_server:
        image: njuptaaa/judge_server
        container_name: judge-server
        restart: always
        read_only: true
        cap_drop:
            - SETPCAP
            - MKNOD
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
            - FSETID
        tmpfs:
            - /tmp
        volumes:
            - $PWD/data/backend/test_case:/test_case:ro
            - $PWD/data/judge_server/log:/log
            - $PWD/data/judge_server/run:/judger
        environment:
            - TOKEN=YOUR_TOKEN_HERE
        ports:
            - "0.0.0.0:8090:8080"
